pref("extensions.{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}.description", "chrome://flashgot/locale/about.properties");
pref("flashgot.Downloader_4_X.quiet", false);
pref("flashgot.GetRight.autostart", false);
pref("flashgot.GetRight.old", false);
pref("flashgot.GetRight.quick", true);
pref("flashgot.GetRight.replaceSpecialChars", true);
pref("flashgot.LeechGet.httpLog", false);
pref("flashgot.altClick", true);
pref("flashgot.gesture", true);
pref("flashgot.gesture.feedback", true);
pref("flashgot.autoReferrer", true);
pref("flashgot.autoStart", true);
pref("flashgot.bgProcessing", true);
pref("flashgot.bypassCombo", true);
pref("flashgot.detect.auto", true);
pref("flashgot.extfilter", false);
pref("flashgot.fakeReferrer", "");
pref("flashgot.firstRunRedirection", true);
pref("flashgot.hide-autotest", true);
pref("flashgot.hide-icons", false);
pref("flashgot.hide-tabs", true);
pref("flashgot.hideDisabledCmds", true);
pref("flashgot.httpauth", false);
pref("flashgot.includeImages", false);
pref("flashgot.interceptAll", false);
pref("flashgot.logEnabled", true);
pref("flashgot.metalink", true);
pref("flashgot.multiQuiet", false);
pref("flashgot.nested-menu", false);
pref("flashgot.omitCookies", false);
pref("flashgot.rsPremium", false);
pref("flashgot.selection.guessPassword", true);
pref("flashgot.redir.anonymous.anonym_to", true);
pref("flashgot.redir.anonymous.anonymz_com", true);
pref("flashgot.redir.anonymous.stealth_to", true);
pref("flashgot.redir.anonymous.sf_net", true);
pref("flashgot.redir.generic.rx", "^https?://(?!web\\.archive\\.org/web/\\d+).*?(\\bhttps?(?::|%3A)(?:%2F|/)+\\w+[^&]*)");
pref("flashgot.redir.generic.exceptions", "");
pref("flashgot.redir.megaupload_com.force", false);
pref("flashgot.redir.generic.enabled", true);
pref("flashgot.redir.rapidshare_com.enabled", true);
pref("flashgot.redir.filesonic_com.enabled", false);

pref("flashgot.appleScriptEncoding", "UTF-8");
pref("flashgot.queryStringSuffix", "");
pref("flashgot.useWine", false);
pref("flashgot.wine.paths", "/usr/bin/wine:/usr/local/bin/wine:/opt/local/bin/wine:/Applications/Darwine/Wine.bundle/Contents/bin/wine");
pref("flashgot.oldSD", false);
pref("flashgot.noDesc", false);

pref("flashgot.media.guessName", true);
pref("flashgot.media.use_iframe_title", false);
pref("flashgot.media.forceNameHack", false);
pref("flashgot.media.statusIcon", true);
pref("flashgot.media.unicode", true);
pref("flashgot.media.enabled", true);
pref("flashgot.media.redirect", 1);
pref("flashgot.media.redirect.joost_com", 0);
pref("flashgot.media.minSize.flv", 500000);
pref("flashgot.media.iconInstalled", false);
pref("flashgot.media.skipAds", true);
pref("flashgot.media.YouTube.autodetect", true);
pref("flashgot.media.YouTube.seek_pos.show", true);
pref("flashgot.media.YouTube.seek_pos.show_ms", false);
pref("flashgot.media.YouTube.seek_pos.compact", true);
pref("flashgot.media.YouTube.flashvars_element_id", "movie_player");
pref("flashgot.media.YouTube.flashvars_element_attr", "flashvars");
pref("flashgot.media.YouTube.decode_signature_func.sandbox", true);
pref("flashgot.media.YouTube.decode_signature_func.auto", true);
pref("flashgot.media.YouTube.stream_url.tidy", false);
pref("flashgot.media.YouTube.stream_url.extra_keep_params", "");
pref("flashgot.media.YouTube.remap_stream_quality", false);
pref("flashgot.media.YouTube.remap_stream_type", false);
pref("flashgot.media.autoCloseDocument", false);
pref("flashgot.media.YouTube.type_sort_order", "video/mp4, video/x-flv, video/webm, video/3gpp, audio/mp4, audio/webm");
pref("flashgot.media.YouTube.remap_type_sort_order", "mp4, flv, webm, 3gp, audio/mp4, audio/webm");
pref("flashgot.media.YouTube.itag_map.quality_sort_key.480", "480");
pref("flashgot.media.YouTube.itag_map.quality_sort_key.480.itags", "59");



pref("flashgot.dmsopts._Built_In_.redir.filesonic_com.enabled", false);
pref("flashgot.dmsopts._Built_In_.invertAltShiftClick", false);
pref("flashgot.dmsopts._Built_In_.overwrite", false);
pref("flashgot.dmsopts._Built_In_.showDM", true);
pref("flashgot.dmsopts._Built_In_.noRedir", false);
pref("flashgot.dmsopts._Built_In_.noRedir.extensions", "\\.(?:gif|jpe?g|png|svg|avi|asf|flv|mov|mp(?:e?g|[34])|wmv|ogg|mk[va]|au|wav|7z|bz2?|gz(?:ip)?|rar|tar|zip|cbr|cbz|exe|msi|iso|dmg|torrent|\\d{3})$");
pref("flashgot.dmsopts.Net_Transport.encode", false);
pref("flashgot.dmsopts.Net_Transport_2.stripHash", true);
pref("flashgot.dmsopts.FlashGet.asciiFilter", true);
pref("flashgot.dmsopts.FlashGet.cookiePersistence", 24);

pref("flashgot.dmsopts.JDownloader.url", "http://127.0.0.1:9666/flashgot");
pref("flashgot.dmsopts.JDownloader.delay", 8);
pref("flashgot.dmsopts.JDownloader.autostart", true);
pref("flashgot.dmsopts.JDownloader.quiet", false);

pref("flashgot.dmsopts.pyLoad.url", "http://127.0.0.1:9666/flashgot");
pref("flashgot.dmsopts.pyLoad.autostart", true);

pref("flashgot.java", "");
pref("flashgot.shredding", false);
pref("flashgot.term.autoClose", -1);